# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup Node
    init: |
      cd my-catalog
      npm install
      npm run build
    command: |
      cd my-catalog
      npm run start
  - name: Setup Python
  - init: |
      cd catalog-generator
      pip install -r requirements.txt



vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-python.python
    - tabnine.tabnine-vscode